### ISSUE TITLE
Create new memory

### ISSUE THREAD

**Issue by lalueders** [lalueders/capstone-project#1]
## Value Proposition

As a user I want to create a new memory by writing down a special moment or a certain situation and store it in order to remember it later.

## Description

- Add a basic form to write down a date, a heading and some text and submit all inputs with a click on a button.
- For now store the data in local storage to use it in further development process

![image](https://user-images.githubusercontent.com/97477326/156589063-33e5fe11-fbbf-4a5c-a048-577258b62289.png)

## Acceptance Criteria

- [ ] Empty form showing up when page loads
- [ ] Form (and button) fit to screen
- [ ] All inputs have a label
- [ ] All inputs have a placeholder-text
- [ ] All inputs are required
- [ ] Heading input is limited to 70 chars
- [ ] Text input is limited to 280 chars
- [ ] Click on button 
  - [ ] submits the form, 
  - [ ] store the input data to local storage
  - [ ] clear all input fields
  - [ ] Error-/success message showing up

## Tasks

- [ ] Create Global Styles
- [ ] Create a Component / Form
  - [ ] Storybook
  - [ ] Test
- [ ] Create Component / Button (create)
  - [ ] Storybook
  - [ ] Test
- [ ] Create local storage hook
  - [ ] /hooks folder
- [ ] Add to app
