### ISSUE TITLE
Show list with memories

### ISSUE THREAD

**Issue by lalueders** [lalueders/capstone-project#2]
## Value Proposition

As a user I want to see a list of my memories because I love to reminisce.

## Description

- Show a list of memories with all submitted memories. 
- For each memory show the date, the headline and the text in a card. 

![image](https://user-images.githubusercontent.com/97477326/156629713-3f8cf5f0-5cde-45cc-a10c-e52ba53b259d.png)

## Acceptance Criteria

- [ ] Empty list showing up if nothing to display
- [ ] One card is displayed for each submitted Form
- [ ] Each memory in the list has...
  - [ ] date
  - [ ] heading
  - [ ] text

## Tasks

- [ ] Create Global Styles
- [ ] Create a Component / List
  - [ ] Add Storybook
  - [ ] Write tests
- [ ] Add to app
