### ISSUE TITLE
Add search bar

### ISSUE THREAD

**Issue by lalueders** [lalueders/capstone-project#28]
**As a user**
**I need** to search all my notes by input some text
**to be able to** to find a certain note even if I don't know when I created my note neither what category was given to it

## Description

![User Story - Add search bar](https://user-images.githubusercontent.com/97477326/159160099-7b564c57-4fae-45e6-bb8d-19ea88740b3c.png)

## Acceptance Criteria

- [ ] search bar is shown on list page
- [ ] search bar includes text-input and search button
- [ ] When I click on button to search, only notes that contain the specified search-text in the title are displayed in the list

## Tasks

- [ ] Add component / SearchBar
  - [ ] Storybook
  - [ ] Test
- [ ] Update page / ShowNotesPage
